import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

function esc(v: any): string {
  return String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const LABELS: [string, string][] = [
  ['first_name', 'First name'], ['firstName', 'First name'],
  ['middle_name', 'Middle name'], ['middleName', 'Middle name'],
  ['last_name', 'Last name'], ['lastName', 'Last name'],
  ['date_of_birth', 'Date of birth'], ['dob', 'Date of birth'],
  ['gender', 'Gender'],
  ['phone', 'Phone'],
  ['residence_state', 'State'], ['stateOfOrigin', 'State'], ['birthstate', 'State'],
  ['birth_lga', 'LGA'],
  ['nin', 'NIN'], ['bvn', 'BVN'],
  ['email', 'Email'],
];

function buildSlip(row: any): string {
  const d = row.safe_response_data ?? {};
  const seen = new Set<string>();
  const rows = LABELS.filter(([key, label]) => {
    if (d[key] == null || d[key] === '' || seen.has(label)) return false;
    seen.add(label);
    return true;
  })
    .map(
      ([key, label]) =>
        `<tr><td>${esc(label)}</td><td><strong>${esc(d[key])}</strong></td></tr>`
    )
    .join('');

  const serviceName = row.verification_services?.name ?? 'Verification';
  const date = new Date(row.created_at).toLocaleString('en-NG');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>DeenByte Verify — Slip ${esc(row.request_reference)}</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;background:#f3f4f6;margin:0;padding:24px;color:#111827}
  .card{max-width:640px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 16px rgba(0,0,0,.08)}
  .head{background:#16a34a;color:#fff;padding:20px 24px;display:flex;align-items:center;gap:12px}
  .logo{width:40px;height:40px;background:#fff;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px}
  .head h1{font-size:18px;margin:0}
  .head p{margin:2px 0 0;font-size:12px;opacity:.9}
  .body{padding:24px}
  .meta{display:flex;flex-wrap:wrap;gap:8px 24px;font-size:13px;color:#4b5563;margin-bottom:16px}
  .badge{display:inline-block;background:#dcfce7;color:#166534;border:1px solid #bbf7d0;border-radius:999px;padding:4px 12px;font-size:12px;font-weight:700}
  table{width:100%;border-collapse:collapse;font-size:14px}
  td{padding:10px 8px;border-bottom:1px solid #e5e7eb;vertical-align:top}
  td:first-child{color:#6b7280;width:40%}
  .foot{padding:16px 24px;background:#f9fafb;font-size:11px;color:#6b7280;text-align:center}
  .print{display:block;margin:16px auto 0;background:#16a34a;color:#fff;border:none;border-radius:10px;padding:12px 28px;font-size:14px;font-weight:700;cursor:pointer}
  @media print{.print{display:none}body{background:#fff;padding:0}.card{box-shadow:none}}
</style>
</head>
<body>
<div class="card">
  <div class="head">
    <div class="logo">🛡️</div>
    <div>
      <h1>DeenByte Verify</h1>
      <p>Fast, secure and reliable identity verification</p>
    </div>
  </div>
  <div class="body">
    <div class="meta">
      <span>Ref: <strong>${esc(row.request_reference)}</strong></span>
      <span>Service: <strong>${esc(serviceName)}</strong></span>
      <span>Date: <strong>${esc(date)}</strong></span>
      <span class="badge">VERIFIED</span>
    </div>
    <table>${rows}</table>
    <button class="print" onclick="window.print()">Print / Save as PDF</button>
  </div>
  <div class="foot">This slip was generated by DeenByte Verify. Data sourced from the official verification provider at the time of request.</div>
</div>
</body>
</html>`;
}

export async function GET(req: Request, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.redirect(new URL('/login', req.url), 302);

  const { data: row, error } = await supabase
    .from('verification_requests')
    .select('slip_base64, request_reference, status, created_at, safe_response_data, verification_services(name)')
    .eq('id', id)
    .eq('user_id', user.id)
    .single();

  if (error || !row || row.status !== 'successful') {
    return NextResponse.json({ error: 'Slip not found.' }, { status: 404 });
  }

  if (row.slip_base64) {
    const pdf = Buffer.from(row.slip_base64, 'base64');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'inline; filename="' + row.request_reference + '.pdf"',
        'Cache-Control': 'private, no-store',
      },
    });
  }

  return new NextResponse(buildSlip(row), {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'private, no-store',
    },
  });
}
