'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { GoogleButton } from '@/components/google-button';
import { createClient } from '@/lib/supabase/client';
import { BrandLogo } from '@/components/brand';

export default function LoginPage() {
  const router = useRouter();
    const supabase = createClient();
      const [email, setEmail] = useState('');
        const [password, setPassword] = useState('');
          const [showPassword, setShowPassword] = useState(false);
            const [error, setError] = useState('');
              const [loading, setLoading] = useState(false);

                const handleLogin = async (e: React.FormEvent) => {
                    e.preventDefault();
                        setError('');

                            if (!/^\S+@\S+\.\S+$/.test(email)) { setError('Enter a valid email address.'); return; }
                                if (!password) { setError('Enter your password.'); return; }

                                    setLoading(true);
                                        const { error } = await supabase.auth.signInWithPassword({ email, password });

                                            if (error) {
                                                  setError(error.message.includes('Invalid') ? 'Invalid email or password.' : error.message);
                                                        setLoading(false);
                                                              return;
                                                                  }

                                                                      router.push('/dashboard');
                                                                          router.refresh();
                                                                            };

                                                                              return (
                                                                                  <main className="min-h-screen flex items-center justify-center px-4 py-10">
                                                                                        <div className="w-full max-w-sm">
                                                                                                <BrandLogo />
                                                                                                        <p className="text-center text-muted text-sm mt-2">Fast, secure and reliable identity verification.</p>

                                                                                                                <div className="card3d p-6 mt-8 shadow-sm">
                                                                                                                          <h1 className="text-lg font-semibold text-dark">Welcome back</h1>
                                                                                                                                    <p className="text-sm text-muted mt-1">Log in to your account</p>

                                                                                                                                              {error && (
                                                                                                                                                          <div className="mt-4 text-sm text-red-600 bg-red-50 border border-red-100 rounded-lg px-3 py-2">{error}</div>
                                                                                                                                                                    )}

                                                                                                                                                                              <form onSubmit={handleLogin} className="mt-4 space-y-4">
                                                                                                                                                                                          <div>
                                                                                                                                                                                                        <label htmlFor="email" className="block text-sm font-medium text-dark mb-1">Email</label>
                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                      id="email" type="email" value={email} autoComplete="email"
                                                                                                                                                                                                                                                      onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"
                                                                                                                                                                                                                                                                      className="w-full rounded-lg border border-border px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                          <label htmlFor="password" className="block text-sm font-medium text-dark mb-1">Password</label>
                                                                                                                                                                                                                                                                                                                                        <div className="relative">
                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                          id="password" type={showPassword ? 'text' : 'password'} value={password}
                                                                                                                                                                                                                                                                                                                                                                                            autoComplete="current-password" onChange={(e) => setPassword(e.target.value)} placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-lg border border-border px-3 py-2.5 pr-16 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="button" onClick={() => setShowPassword(!showPassword)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-semibold text-muted hover:text-dark"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {showPassword ? 'HIDE' : 'SHOW'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="flex items-center gap-2 text-sm text-muted">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="checkbox" defaultChecked className="h-4 w-4 rounded accent-primary" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Remember me
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/forgot-password" className="text-sm font-medium text-primary hover:underline">Forgot password?</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit" disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full rounded-lg bg-primary py-2.5 text-sm font-semibold text-white hover:bg-primary-dark disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? 'Logging in…' : 'Log in'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
              <GoogleButton />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-center text-sm text-muted mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Don&apos;t have an account?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/register" className="font-semibold text-primary hover:underline">Create account</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer className="fixed bottom-0 inset-x-0 z-10 py-3 text-center text-xs text-muted bg-light/95 border-t border-border">
        <a href="/privacy" className="underline">Privacy Policy</a> · <a href="/terms" className="underline">Terms of Service</a> · <a href="mailto:deenbyte.technologies@gmail.com" className="underline">Support</a>
      </footer>
</main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }