'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import { BrandLogo } from '@/components/brand';

export default function RegisterPage() {
  const router = useRouter();
    const supabase = createClient();
      const [email, setEmail] = useState('');
        const [password, setPassword] = useState('');
          const [confirm, setConfirm] = useState('');
            const [error, setError] = useState('');
              const [loading, setLoading] = useState(false);

                const handleRegister = async (e: React.FormEvent) => {
                    e.preventDefault();
                        setError('');

                            if (!/^\S+@\S+\.\S+$/.test(email)) { setError('Enter a valid email address.'); return; }
                                if (password.length < 6) { setError('Password must be at least 6 characters.'); return; }
                                    if (password !== confirm) { setError('Passwords do not match.'); return; }

                                        setLoading(true);
                                            const { data, error } = await supabase.auth.signUp({ email, password });

                                                if (error) { setError(error.message); setLoading(false); return; }
                                                    if (!data.session) { setError('Check your email to confirm your account, then log in.'); setLoading(false); return; }

                                                        router.push('/dashboard');
                                                            router.refresh();
                                                              };

                                                                return (
                                                                    <main className="min-h-screen flex items-center justify-center px-4 py-10">
                                                                          <div className="w-full max-w-sm">
                                                                                  <BrandLogo />

                                                                                          <div className="card3d p-6 mt-8 shadow-sm">
                                                                                                    <h1 className="text-lg font-semibold text-dark">Create your account</h1>
                                                                                                              <p className="text-sm text-muted mt-1">Start verifying identities in minutes</p>

                                                                                                                        {error && (
                                                                                                                                    <div className="mt-4 text-sm text-red-600 bg-red-50 border border-red-100 rounded-lg px-3 py-2">{error}</div>
                                                                                                                                              )}

                                                                                                                                                        <form onSubmit={handleRegister} className="mt-4 space-y-4">
                                                                                                                                                                    <div>
                                                                                                                                                                                  <label htmlFor="email" className="block text-sm font-medium text-dark mb-1">Email</label>
                                                                                                                                                                                                <input
                                                                                                                                                                                                                id="email" type="email" value={email} autoComplete="email"
                                                                                                                                                                                                                                onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"
                                                                                                                                                                                                                                                className="w-full rounded-lg border border-border px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                    <label htmlFor="password" className="block text-sm font-medium text-dark mb-1">Password</label>
                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                  id="password" type="password" value={password} autoComplete="new-password"
                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPassword(e.target.value)} placeholder="Minimum 6 characters"
                                                                                                                                                                                                                                                                                                                                                                  className="w-full rounded-lg border border-border px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="confirm" className="block text-sm font-medium text-dark mb-1">Confirm password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                    id="confirm" type="password" value={confirm} autoComplete="new-password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setConfirm(e.target.value)} placeholder="Repeat password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-lg border border-border px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="submit" disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full rounded-lg bg-primary py-2.5 text-sm font-semibold text-white hover:bg-primary-dark disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? 'Creating account…' : 'Create account'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-center text-sm text-muted mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Already have an account?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/login" className="font-semibold text-primary hover:underline">Log in</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <footer className="fixed bottom-0 inset-x-0 z-10 py-3 text-center text-xs text-muted bg-light/95 border-t border-border">
        <a href="/privacy" className="underline">Privacy Policy</a> · <a href="/terms" className="underline">Terms of Service</a> · <a href="mailto:deenbyte.technologies@gmail.com" className="underline">Support</a>
      </footer>
</main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }